name: ci the api

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Check for test failures
        if: failure() # Run only if a previous step has failed
        run: |
          echo "⚠️ Tests failed. Blocking pull request merge."
          echo "::set-output name=fail-message::⚠️ Tests failed."

      - name: Create status check failure
        if: failure() # Create a status check failure only if tests failed
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.check-for-test-failures.outputs.fail-message }}'
            })
            github.actions.setFailed('Tests failed')
